###
GET http://localhost:8080/api/players/{{pUUID}}
Accept: application/json

###
GET http://localhost:8080/api/players/{{gameName}}/{{tagName}}
Accept: application/json


###
GET https://europe.api.riotgames.com/riot/account/v1/accounts/by-riot-id/{{gameName}}/{{tagName}}
X-Riot-Token: {{token}}
Accept: application/json

###
GET https://europe.api.riotgames.com/riot/account/v1/accounts/by-puuid/{{pUUID}}
X-Riot-Token: {{token}}
Accept: application/json
