spring:
  application:
    name: LoLchiement
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /openapi.yaml
app:
  frontend-url: http://localhost:3000
  api-url: http://localhost:8080
cDragon:
  api:
    base: raw.communitydragon.org
    assets:
      base:
        name: /latest/game/assets/
      challenges:
        name: challenges/config/
riot:
  dev:
    key: ${RIOT_TOKEN}
  region:
    europe: europe
    euw: euw1
  api:
    base: api.riotgames.com/
    key:
      lol:
        challenges:
          name: lol/challenges/v1/
      riot:
        player:
          name: riot/account/v1/accounts/
server:
  port: 8080
logging:
  level:
    com.lolchievement: DEBUG
