openapi: 3.0.1
info:
  title: LoLchievement API
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  ### Challenge
  /api/challenges/{language}:
    get:
      operationId: getAllChallenges
      summary: Get all challenges
      tags:
        - Challenge
      parameters:
        - name: language
          in: path
          required: true
          schema:
            type: string
          description: Local language code (e.g., en_US, de_DE)
      responses:
        '200':
          description: Challenge information
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChallengeDTO'
        '400':
          description: Invalid language parameter
        '429':
          description: Rate limit exceeded
        '502':
          description: External service error
        '500':
          description: Internal server error

  /api/challenges/player/{pUUID}/{language}:
    get:
      operationId: getPlayerChallengeByPUUID
      summary: Get all player challenges by pUUID
      tags:
        - Challenge
      parameters:
        - name: pUUID
          in: path
          required: true
          schema:
            type: string
          description: Player UUID
        - name: language
          in: path
          required: true
          schema:
            type: string
          description: Local language code
      responses:
        '200':
          description: Player challenge information
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PlayerChallengeDTO'
        '400':
          description: Invalid parameters
        '404':
          description: Player not found
        '429':
          description: Rate limit exceeded
        '502':
          description: External service error
        '500':
          description: Internal server error

  /api/challenges/{challengeId}/{language}:
    get:
      operationId: getChallengeDetailByChallengeId
      summary: Get challenge detail by challenge id
      tags:
        - Challenge
      parameters:
        - name: challengeId
          in: path
          required: true
          schema:
            type: string
          description: Challenge ID
        - name: language
          in: path
          required: true
          schema:
            type: string
          description: Local language code
      responses:
        '200':
          description: Detailed challenge information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChallengeDTO'
        '400':
          description: Invalid challenge ID format
        '404':
          description: Challenge not found
        '429':
          description: Rate limit exceeded
        '502':
          description: External service error
        '500':
          description: Internal server error

  /api/challenges/token/{challengeId}:
    get:
      operationId: getChallengeToken
      summary: Get challenge token image by challenge id and tier
      tags:
        - Challenge
      parameters:
        - name: challengeId
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: Challenge ID
        - name: tierDTO
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/TierDTO'
          description: Optional tier (defaults to CHALLENGER)
      responses:
        '200':
          description: Challenge token image
          content:
            image/png:
              schema:
                type: string
                format: binary
        '400':
          description: Invalid challenge ID or tier
        '404':
          description: Challenge token not found
        '500':
          description: Internal server error

  ### Player
  /api/players/{id}:
    get:
      operationId: getPlayerById
      summary: Get player by PUUID
      tags:
        - Player
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Player UUID
      responses:
        '200':
          description: Player information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerDTO'
        '400':
          description: Invalid player ID
        '404':
          description: Player not found
        '500':
          description: Internal server error

  /api/players/{gameName}/{tagName}:
    get:
      operationId: getPlayerByGameAndTagName
      summary: Get player by gameName and tagName
      tags:
        - Player
      parameters:
        - name: gameName
          in: path
          required: true
          schema:
            type: string
          description: In-game player name
        - name: tagName
          in: path
          required: true
          schema:
            type: string
          description: Player tag name
      responses:
        '200':
          description: Player information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerDTO'
        '400':
          description: Invalid game name or tag name
        '404':
          description: Player not found
        '500':
          description: Internal server error

components:
  schemas:
    PlayerDTO:
      $ref: './components/schemas/playerDTO.yaml'
    PlayerChallengeDTO:
      $ref: './components/schemas/playerChallengeDTO.yaml'
    ChallengeDTO:
      $ref: './components/schemas/challengeDTO.yaml'
    ChallengeThresholdDTO:
      $ref: './components/schemas/challengeThresholdDTO.yaml'
    State:
      $ref: './components/schemas/state.yaml'
    TierDTO:
      $ref: './components/schemas/tierDTO.yaml'