openapi: 3.0.1
info:
  title: LoLchievement API
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  ### Achievement
  /api/achievements/player/{pUUID}/{language}:
    get:
      operationId: getPlayerAchievementByPUUID
      summary: Get all player achievements by pUUID
      tags:
        - Achievement
      parameters:
        - name: pUUID
          in: path
          required: true
          schema:
            type: string
          description: Player uuid
        - name: language
          in: path
          required: true
          schema:
            type: string
          description: local language
      responses:
        '200':
          description: Player achievement information
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PlayerAchievementDTO'
  /api/achievements/{challengeId}/{language}:
    get:
      operationId: getAchievementDetailByChallengeId
      summary: Get achievement detail by challenge id
      tags:
        - Achievement
      parameters:
        - name: challengeId
          in: path
          required: true
          schema:
            type: string
          description: Player uuid
        - name: language
          in: path
          required: true
          schema:
            type: string
          description: local language
      responses:
        '200':
          description: Detailed achievement information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AchievementDTO'
  /api/achievements/token/{challengeId}:
    get:
      operationId: getChallengeToken
      summary: Get challenge token image by challenge id and tier
      tags:
        - Achievement
      parameters:
        - name: challengeId
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: Challenge ID
        - name: tier
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/Tier'
          description: Optional tier
      responses:
        '200':
          description: Challenge token image
          content:
            image/png:
              schema:
                type: string
                format: binary

  ### Player
  /api/players/{id}:
    get:
      operationId: getPlayerById
      summary: Get player by PUUID
      tags:
        - Player
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Player uuid
      responses:
        '200':
          description: Player information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerDTO'
  /api/players/{gameName}/{tagName}:
    get:
      operationId: getPlayerByGameAndTagName
      summary: Get player by gameName and tagName
      tags:
        - Player
      parameters:
        - name: gameName
          in: path
          required: true
          schema:
            type: string
          description: In game player name
        - name: tagName
          in: path
          required: true
          schema:
            type: string
          description: Player tag name
      responses:
        '200':
          description: Player information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerDTO'

components:
  schemas:
    PlayerDTO:
      $ref: './components/schemas/playerDTO.yaml'
    PlayerAchievementDTO:
      $ref: './components/schemas/playerAchievementDTO.yaml'
    AchievementDTO:
      $ref: './components/schemas/AchievementDTO.yaml'
    Tier:
      $ref: './components/schemas/tier.yaml'
