openapi: 3.0.1
info:
  title: LoLchievement API
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  ### Achievement
  /api/achievements:
    get:
      operationId: getAllAchievements
      summary: Get all Achievement
      tags:
        - Achievement
      responses:
        '200':
          description: Achievement information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AchievementDTO'
  /api/achievements/{id}:
    get:
      operationId: getAchievementById
      summary: Get achievement by id
      tags:
        - Achievement
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Achievement uuid
      responses:
        '200':
          description: Achievement information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AchievementDTO'

  ### Player
  /api/players/{id}:
    get:
      operationId: getPlayerById
      summary: Get player by PUUID
      tags:
        - Player
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Player uuid
      responses:
        '200':
          description: Player information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerDTO'
  /api/players/{gameName}/{tagName}:
    get:
      operationId: getPlayerByGameAndTagName
      summary: Get player by gameName and tagName
      tags:
        - Player
      parameters:
        - name: gameName
          in: path
          required: true
          schema:
            type: string
          description: In game player name
        - name: tagName
          in: path
          required: true
          schema:
            type: string
          description: Player tag name
      responses:
        '200':
          description: Player information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerDTO'

components:
  schemas:
    PlayerDTO:
      $ref: './components/schemas/playerDTO.yaml'
    AchievementDTO:
      $ref: './components/schemas/achievementDTO.yaml'
